---
- hosts: all
  remote_user: pi
  tasks:
    - name: Add the user '{{target_user}}' with a specific uid and a primary group of 'sudo'
      user:
        name: "{{target_user}}"
        shell: /bin/bash
        groups: sudo
        append: yes
      become: yes
    - name: Add {{ target_user }} user to the sudoers
      copy:
          dest: "/etc/sudoers.d/{{ target_user }}"
          content: "{{ target_user }}  ALL=(ALL)  NOPASSWD: ALL"
      become: yes
    - name: Set authorized key took from file
      authorized_key:
        user: "{{target_user}}"
        key: "{{ lookup('file', '/credentials/ssh/id_rsa.pub') }}"
        state: present
      become: yes
    # - name: Change autologin user to {{ target_user }}
    #   lineinfile:
    #     dest=/etc/lightdm/lightdm.conf
    #     regexp='^autologin-user'
    #     line="autologin-user={{ target_user }}"
    #     state=present
    #     backup=yes
    # - name: Disable Password Authentication
    #   lineinfile:
    #     dest=/etc/ssh/sshd_config
    #     regexp='^PasswordAuthentication'
    #     line="PasswordAuthentication no"
    #     state=present
    #     backup=yes
    #   become: yes
    #   notify:
    #     - restart ssh
    # - name: Disable Root Login
    #   lineinfile:
    #     dest=/etc/ssh/sshd_config
    #     regexp='^PermitRootLogin'
    #     line="PermitRootLogin no"
    #     state=present
    #     backup=yes
    #   become: yes
    #   notify:
    #     - restart ssh

  handlers:
    - name: restart ssh
      service:
        name=ssh
        state=restarted
      become: 
        yes