---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
    - name: update *
      command: apt-get update
      become: True
    - name: upgrade *
      command: apt-get upgrade -y
      become: True
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - kodi
        # - kodi-pvr-dvblink
        - kodi-pvr-hts
        # - kodi-peripheral-joystick
      become: True
    # - name: enable autostart #TODO: fix
    #   command: echo "@kodi" >>   /home/pi/.config/lxsession/LXDE-pi/autostart
    #   become: True
    - name: Ensure group "input" exists
      group:
        name: input
        system: True
        state: present
      become: True
    # - name: add input to rules.d
    #   command: echo "SUBSYSTEM==input, GROUP=input, MODE=0660 KERNEL==tty[0-9]*, GROUP=tty, MODE=0660" >> /etc/udev/rules.d/99-input.rules
    #   become: True
    - name: enable service
      command: systemctl unmask kodi.service && systemctl enable kodi.service
      become: True
    # - name: Download magic dragon
    #   get_url:
    #     url: http://mavericktv.net/mavrepo/repository.maverickrepo-3.5.zip
    #     dest: /home/pi/repository.maverickrepo-3.5.zip
    #   become: True
    # - name: put kodi.zip settings
    #   copy:
    #     src: kodi.zip
    #     dest: /tmp/kodi.zip
    #   become: True
    # - name: mv kodi.zip
    #   command: mv /tmp/kodi.zip /home/pi/kodi.zip 
    #   become: True
    # - name: clear settings
    #   command: rm -rf /home/pi/.kodi 
    #   become: True
    # - name: Unarchive a file that is already on the remote machine
    #   unarchive:
    #     src: /home/pi/kodi.zip
    #     dest: /home/pi/
    #     remote_src: yes
    #   become: True
    # - name: chown settings
    #   command: chown -R pi:pi /home/pi/.kodi
    #   become: True
    